AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/**/*
    - db/migrate/*
    - config/**/*
    - config.ru
    - tmp/**/*
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - channels/application_cable/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Lambda:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

AccessorMethodName:
  Enabled: false

Documentation:
  Enabled: false

AndOr:
  Enabled: false

BlockNesting:
  Max: 5

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

LineLength:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

MethodLength:
  Enabled: false

ParameterLists:
  Max: 12

Style/SymbolArray:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  
MixinUsage:
  Include:
    - app/**/*.rb
