inherit_from:
  - .rubocop_airbnb.yml

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
    - db/**/*
    - db/migrate/*
    - config/**/*
    - config.ru
    - tmp/**/*
    - 'vendor/**/*'
    - Gemfile
    - Rakefile
    - channels/application_cable/*

MixinUsage:
  Include:
    - app/**/*.rb
